apiVersion: v1
kind: Namespace
metadata:
  name: aegisops-system
  labels:
    app.kubernetes.io/part-of: aegisops
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    app.kubernetes.io/part-of: aegisops-demo
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: observability
